server:
  port: 10003
spring:
  application:
    name: kafkacloudstreamconsumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: 10.62.11.73:9092
          auto-create-topics: true
      bindings:
        input:
          destination: cloudstream
          group: kcsc-group
          consumer:
            partitioned: true
      instance-count: 2
